pipeline:
  restore_cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ~/.gradle
    volumes:
      - /tmp/cache:/cache

  initialize:
    image: martinq/gradle
    commands:
      - java -version

  build:
    image: martinq/gradle
    commands:
      - ./gradlew dependencies -s

  rebuild_cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ~/.gradle
    volumes:
      - /tmp/cache:/cache
