workspace:
  base: /drone
  path: qspring-utils

pipeline:
  restore_cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /drone/gradle
    volumes:
      - /tmp/cache:/cache

  initialize:
    image: martinq/gradle
    commands:
      - java -version

  build:
    image: martinq/gradle
    environment:
      - GRADLE_USER_HOME=/drone/gradle
    commands:
      - du -sh /drone/gradle
      - ./gradlew assemble
      - du -sh /drone/gradle
    secrets: 
      - SIGNING_KEYID
      - SIGNING_PASSWORD

  before_cache:
    image: martinq/gradle
    commands:
      - rm -f workspace/gradle/caches/modules-2/modules-2.lock
      - rm -rf workspace/gradle/caches/*/plugin-resolution/

  rebuild_cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /drone/gradle
    volumes:
      - /tmp/cache:/cache
