workspace:
  base: /drone
  path: qspring-utils

pipeline:
  restore_cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /drone/gradle
      - /drone/qspring-utils/build
    volumes:
      - /tmp/cache:/cache

  before_build:
    image: martinq/gradle
    commands:
      - java -version
      - mkdir -p /drone/gradle
      - du -sh /drone/gradle
      - ls -al /cache/martinq108
    volumes:
      - /tmp/cache:/cache

  build:
    image: martinq/gradle
    environment:
      - GRADLE_USER_HOME=/drone/gradle
    secrets: 
      - SIGNING_KEYID
      - SIGNING_PASSWORD
    commands:
      - ./gradlew assemble

  after_build:
    image: martinq/gradle
    commands:
      - du -sh /drone/gradle

  before_cache:
    image: martinq/gradle
    commands:
      - rm -f workspace/gradle/caches/modules-2/modules-2.lock
      - rm -rf workspace/gradle/caches/*/plugin-resolution/

  rebuild_cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /drone/gradle
      - /drone/qspring-utils/build
    volumes:
      - /tmp/cache:/cache
