workspace:
  base: /workspace
  path: qspring-utils

pipeline:
  restore_cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /workspace/gradle
    volumes:
      - /tmp/cache:/cache

  initialize:
    image: martinq/gradle
    commands:
      - java -version

  build:
    image: martinq/gradle
    environment:
      - GRADLE_USER_HOME=/workspace/gradle
    commands:
      - du -sh /workspace/gradle
      - ./gradlew assemble
      - du -sh /workspace/gradle
    secrets: 
      - SIGNING_KEYID
      - SIGNING_PASSWORD

  rebuild_cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /workspace/gradle
    volumes:
      - /tmp/cache:/cache
